forum/authors/urls.py
from django.urls import path
from . import views
from .views import SearchAuthorView

app_name = 'authors'

urlpatterns = [
    path('', views.AuthorListView.as_view(), name='author_list_view'),
    path('<int:pk>', views.AuthorDetailView.as_view(), name='author_detail_view'),
    path('followers/<int:pk>', views.AuthorFollowersListView.as_view(), name='followers_list_view'),
    path('following/<int:pk>', views.AuthorFollowingListView.as_view(), name='following_list_view'),
    path('filter_by_followers/', views.AuthorFilterByFollowersAmount.as_view(), name='author_filter_by_followers'),
    path('search_author/', SearchAuthorView.as_view(), name='search_author'),

]

forum/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main.views import pageNotFound


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls', namespace='main')),
    path('account/', include('account.urls', namespace='account')),
    path('authors/', include('authors.urls', namespace='authors')),
    path('captcha/', include('captcha.urls')),
]


handler404 = pageNotFound


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/forum/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

forum/authors/models.py
from django.db import models

# Create your models here.

forum/authors/forms.py
from django import forms

from account.models import Author

forum/authors/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse

from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView

from account.models import Author
from authors.utils import AuthorFollowingFollowersListMixin
from main.models import Post


class AuthorListView(AuthorFollowingFollowersListMixin, ListView):
    extra_context = {'headline': 'Список пользователей'}
    template_name = 'authors/ordering_link.html'

    def get_queryset(self):
        current_user_id = self.request.user.id
        queryset = Author.objects.exclude(id=current_user_id)
        return queryset


class AuthorFilterByFollowersAmount(AuthorListView, AuthorFollowingFollowersListMixin, ListView):

    def get_queryset(self):
        return super().get_queryset().order_by('-following')


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'authors/author_detail_view.html'

    def get(self, request, *args, **kwargs):
        other_user = self.get_object()
        try:
            current_user = Author.objects.get(user_name=request.user.user_name)
            if current_user.id == other_user.id:
                return redirect('account:personal_profile')
        except AttributeError:
            pass
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        other_user = self.get_object()
        context = super().get_context_data(**kwargs)
        context['following'] = other_user.followers.count()
        context['followers'] = other_user.following.count()
        context['posts_amount'] = Post.objects.filter(author=other_user).count()
        context['days_registered'] = (timezone.now() - other_user.created).days
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        other_user = self.get_object()
        current_user = Author.objects.get(user_name=request.user.user_name)
        following = other_user.following.all()
        if str(other_user.user_name) != str(current_user.user_name):
            if current_user in following:
                other_user.following.remove(current_user.id)
            else:
                other_user.following.add(current_user.id)
            other_user.save()
            current_user.save()

        return redirect(request.META.get('HTTP_REFERER', '/'))


class AuthorFollowersListView(AuthorFollowingFollowersListMixin, ListView):
    extra_context = {'headline': 'Список подписчиков'}

    def get_queryset(self):
        user_obj = Author.objects.get(id=int(str(self.request).split('/')[-1].strip("'>")))
        queryset = user_obj.following.all()
        return queryset


class AuthorFollowingListView(AuthorFollowingFollowersListMixin, ListView):
    extra_context = {'headline': 'Список подписок'}

    def get_queryset(self):
        user_obj = self.request.user
        queryset = user_obj.followers.all()
        return queryset


class SearchAuthorView(DetailView):
    template_name = 'authors/author_detail_view.html'
    model = Author
    queryset = Author.objects.all()

    def get_object(self, queryset=None):
        query = self.request.GET.get('q')
        try:
            author = Author.objects.get(user_name__iexact=query)
            return author
        except Author.DoesNotExist:
            pass

    def get(self, request, *args, **kwargs):
        author = self.get_object()
        if author:
            url = reverse('authors:author_detail_view', kwargs={'pk': author.pk})
            return HttpResponseRedirect(url)
        else:
            return redirect(request.META.get('HTTP_REFERER'))

forum/authors/templates/authors/author_detail_view.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}

    <link rel="stylesheet" href="{% static 'main/css/personal_profile.css' %}" />


    <section class="section about-section gray-bg" id="about">
            <div class="container">

                <form method="post">
                    {% csrf_token %}

                    {% if user in author.following.all %}
                    <button class="btn btn-sm btn-primary btn-follow" data-slug="{{ profile.slug }}"
                            style="margin-bottom: 2%">
                        Отписаться
                    </button>
                    {% else %}

                    <button class="btn btn-sm btn-primary btn-follow" data-slug="{{ profile.slug }}"
                            style="margin-bottom: 2%">
                        Подписаться
                    </button>
                    {% endif %}

                </form>
                <h5><a href="{% url 'authors:followers_list_view' author.pk %}">Подписчики</a>: {{ author.following.count }}</h5>


                <div class="row align-items-center flex-row-reverse">
                    <div class="col-lg-6">
                        <div class="about-text go-to">
                            <h3 class="dark-color">Имя: {{ author.user_name }}</h3>
                            <h6 class="theme-color lead">{{ user.short_summary }}</h6>
                            <p>{{ author.profile_information }}</p>
                            <div class="row about-list">
                                <div class="col-md-6">

                                    <div class="media">
                                        <label>Страна</label>
                                        <p>
                                            {% if author.country and author.country  %}
                                                {{ author.country }}
                                            {% else %}
                                                Неизвестно
                                            {% endif %}

                                        </p>
                                    </div>


                                    <div class="media">
                                        <label>Адрес</label>
                                        <p>
                                            {% if author.city %}
                                                {{ author.city }}
                                            {% else %}
                                                Неизвестно
                                            {% endif %}
                                        </p>
                                    </div>

                                </div>
                                <div class="col-md-6">

                                    <div class="media">
                                        <label>Почта</label>
                                        <p>
                                            {% if author.email %}
                                            {{ author.email }}
                                            {% else %}
                                            Неизвестно
                                            {% endif %}
                                        </p>
                                    </div>


                                    <div class="media">
                                        <label>Телефон</label>
                                        <p>
                                            {% if author.mobile %}
                                            {{ author.mobile }}
                                            {% else %}
                                            Неизвестно
                                            {% endif %}
                                        </p>
                                    </div>

                                    <div class="media">
                                        <label>Telegram</label>
                                        {% if author.telegram_link %}
                                        <a href="{{ author.telegram_link }}" class="media-link"><p>{{ author.telegram_link }}</p></a>
                                        {% else %}
                                        Неизвестно
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about-avatar">
                            {% if not author.profile_photo %}
                                <img style="width: 315px; height: 315px" src="https://thumbs.dreamstime.com/b/%D0%B7%D0%BD%D0%B0%D1%87%D0%BE%D0%BA-%D0%BF%D0%BE-%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E-%D0%BF%D0%BB%D0%BE%D1%81%D0%BA%D0%B8%D0%B9-%D0%B0%D0%B2%D0%B0%D1%82%D0%B0%D1%80-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8F-%D1%81%D0%BE%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80-184330869.jpg" title="" alt="">

                            {% else %}
                                <img src="{{ author.profile_photo.url }}" title="{{ author.username }}" alt="Фото {{ author.username }}" style="width: 315px; height: 315px">
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="counter">
                    <div class="row">
                        <div class="col-6 col-lg-3">
                            <div class="count-data text-center">
                                <h6 class="count h2" data-to="500" data-speed="500">{{ followers }}</h6>
                                <p class="m-0px font-w-600">Подписчиков</p>
                            </div>
                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="count-data text-center">
                                <h6 class="count h2" data-to="150" data-speed="150">{{ following }}</h6>
                                <p class="m-0px font-w-600">Подписок</p>
                            </div>
                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="count-data text-center">
                                <h6 class="count h2" data-to="850" data-speed="850">{{ posts_amount }}</h6>
                                <p class="m-0px font-w-600">Постов</p>
                            </div>
                        </div>
                        <div class="col-6 col-lg-3">
                            <div class="count-data text-center">
                                <h6 class="count h2" data-to="190" data-speed="190">{{ days_registered }}</h6>
                                <p class="m-0px font-w-600">Дней на сайте</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


{% endblock %}

forum/authors/templates/authors/authors_list_view.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}

<link rel="stylesheet" href="{% static 'main/css/authors_list_view.css' %}">
<link rel="stylesheet" href="{% static 'main/css/posts.css' %}">

    <h1 class="header-top">{{ headline }}</h1>
    {% block order %}

    {% endblock %}


	<table>
		<thead>
			<tr>
				<th>Ник</th>
				<th>Дата создания аккаунта</th>
				<th>Фото профиля</th>
				<th>Информация о себе</th>
			</tr>
		</thead>
		<tbody>


			{% for author in authors %}
			<tr>
				<td class="list_item"><a href="{{ author.get_absolute_url }}">{{ author.user_name }}</a></td>
				<td class="list_item">{{ author.created }}</td>

                {% if not author.profile_photo %}
                    <td class="list_item"><img src="https://thumbs.dreamstime.com/b/%D0%B7%D0%BD%D0%B0%D1%87%D0%BE%D0%BA-%D0%BF%D0%BE-%D1%83%D0%BC%D0%BE%D0%BB%D1%87%D0%B0%D0%BD%D0%B8%D1%8E-%D0%BF%D0%BB%D0%BE%D1%81%D0%BA%D0%B8%D0%B9-%D0%B0%D0%B2%D0%B0%D1%82%D0%B0%D1%80-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8F-%D1%81%D0%BE%D1%86%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80-184330869.jpg" title="" alt=""></td>
                {% else %}
                    <td class="list_item"><img src="{{ author.profile_photo.url }}" alt="Фото профиля"></td>
                {% endif %}
                {% if author.profile_information  %}
                <td class="list_item">{{ author.profile_information|truncatewords:20 }}</td>
                {% else %}
                <td class="list_item">Автор не добавил личную информацию</td>
                {% endif %}
			</tr>

			{% endfor %}

		</tbody>
	</table>

{% include 'main/pagination.html' %}

{% endblock %}

forum/authors/templates/authors/ordering_link.html
{% extends 'authors/authors_list_view.html' %}
{% block order %}
    <h5 style="text-align: center; margin-top: 20px;"><a href="{% url 'authors:author_filter_by_followers' %}">Фильтровать по количеству подписчиков</a></h5>
{% endblock %}