forum/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from . import views
from account.forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm

app_name = 'account'

urlpatterns = [
    path('login/', views.MyLoginView.as_view(template_name='account/login.html',
                                             form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),

    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>', views.account_activate, name='activate'),
    path('personal_profile/', views.personal_profile_view, name='personal_profile'),
    path('personal_profile/edit_details/', views.edit_details, name='edit_details'),
    path('personal_profile/delete_photo/', views.delete_photo, name='delete_photo'),

    # deleting user
    path('personal_profile/delete_user/', views.delete_user, name='delete_user'),
    path('personal_profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"),
         name='delete_confirmation'),

    # restoring user account
    path('restore/', views.enable_user, name='restore'),

    # password reset
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                                                     success_url='password_reset_email_confirm',
                                                                     email_template_name=
                                                                     'account/password_reset/password_reset_email.html',
                                                                     form_class=PwdResetForm), name='pwdreset'
         ),

    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                     success_url='/account/password_reset_complete/',
                                                     form_class=PwdResetConfirmForm), name='password_reset_confirm'),

    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),

    path('password_reset_confirm/Og/password_reset_complete/',
         TemplateView.as_view(template_name='account/password_reset/reset_status.html'), name='password_reset_complete'),

    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),

]

forum/authors/urls.py
from django.urls import path
from . import views
from .views import SearchAuthorView

app_name = 'authors'

urlpatterns = [
    path('', views.AuthorListView.as_view(), name='author_list_view'),
    path('<int:pk>', views.AuthorDetailView.as_view(), name='author_detail_view'),
    path('followers/<int:pk>', views.AuthorFollowersListView.as_view(), name='followers_list_view'),
    path('following/<int:pk>', views.AuthorFollowingListView.as_view(), name='following_list_view'),
    path('filter_by_followers/', views.AuthorFilterByFollowersAmount.as_view(), name='author_filter_by_followers'),
    path('search_author/', SearchAuthorView.as_view(), name='search_author'),

]

forum/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from main.views import pageNotFound


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls', namespace='main')),
    path('account/', include('account.urls', namespace='account')),
    path('authors/', include('authors.urls', namespace='authors')),
    path('captcha/', include('captcha.urls')),
]


handler404 = pageNotFound


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/forum/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

forum/main/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import cache_page

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('category/<slug:slug>/', views.category_detail, name='category'),
    path('category/posts/<slug:subcategory_slug>/', views.subcategory_post, name='subcategory_post'),
    path('category/posts/delete/<int:pk>', views.PostDeleteView.as_view(), name='delete_post'),
    path('category/posts/update/<int:pk>', views.PostUpdateView.as_view(), name='edit_post'),
    path('feedback/', views.FeedBackView.as_view(), name='feedback'),
]

forum/main/models.py
from account.models import Author
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class BlogCategory(models.Model):
    """
    This model describes a category name
    """

    category_name = models.CharField(max_length=255, unique=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=255, unique=True, verbose_name='Слаг категории')
    category_photo = models.ImageField(blank=True, verbose_name='Изображение категории')

    class Meta:
        verbose_name = _('Категория')
        verbose_name_plural = _('Категории')
        ordering = ('category_name', )

    def get_absolute_url(self):
        return reverse("main:category", args=[self.slug])

    def __str__(self):
        return self.category_name


class SubCategory(models.Model):
    category = models.ForeignKey(BlogCategory, on_delete=models.CASCADE, verbose_name='Внешний ключ категории')
    sub_category_name = models.CharField(max_length=255, verbose_name='Название подкатегории')
    slug = models.SlugField(max_length=255, verbose_name='Слаг подкатегории')

    def __str__(self):
        return self.sub_category_name

    class Meta:
        verbose_name = _('Подкатегория')
        verbose_name_plural = _('Подкатегории')
        ordering = ('-sub_category_name', )

    def get_absolute_url(self):
        return reverse("main:subcategory_post",  args=[self.slug])


class Post(models.Model):
    category = models.ForeignKey(SubCategory, on_delete=models.CASCADE, verbose_name='Внешний ключ подкатегории')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Внешний ключ автора')
    title = models.CharField(max_length=255, verbose_name='Заголовок поста')
    text = models.TextField(verbose_name='Пост')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время публикации поста')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время редактирования')
    is_published = models.BooleanField(default=True, verbose_name='Опубликован', help_text='Опубликован ли пост')

    def get_absolute_url(self):
        return reverse('main:edit_post', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('Пост')
        verbose_name_plural = _('Посты')
        ordering = ('-created_at', 'author')


class FeedBack(models.Model):

    text = models.TextField(verbose_name='Текст обратной связи')

    def __str__(self):
        return self.text

forum/main/forms.py
from account.models import Author
from main.models import Post, FeedBack
from django import forms
from captcha.fields import CaptchaField


class AddCommentForm(forms.ModelForm):

    title = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3',
               'placeholder': 'Заголовок', 'id': 'form-lastname', 'name': 'parent'}), max_length=255,
        label='Заголовок')

    text = forms.CharField(required=False,
                           widget=forms.Textarea(attrs={
                                                        'class': 'form-control',
                                                        'id': 'exampleFormControlTextarea1',
                                                        'rows': '3',
                                                        'placeholder': 'Оставить комментарий'
                           }), label='Комментарий')

    class Meta:
        model = Post
        fields = ('title', 'text')


class FeedBackForm(forms.ModelForm):
    text = forms.CharField(required=True,
                           widget=forms.Textarea(attrs={
                               'class': 'form-control',
                               'id': 'exampleFormControlTextarea1',
                               'rows': '5',
                               'placeholder': 'Задайте вопрос'
                           }), label='Ваш вопрос или пожелание')

    captcha = CaptchaField(error_messages={'invalid': "Капча введена неверно. Пожалуйста, попробуйте еще раз."})

    class Meta:
        model = FeedBack
        fields = ('text',)

forum/main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import mail_admins
from django.core.paginator import Paginator
from django.db.models import Max, Count, Subquery, OuterRef
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic import TemplateView, UpdateView, DeleteView, FormView
from django.contrib import messages
from account.models import Author
from main.forms import AddCommentForm, FeedBackForm
from main.models import BlogCategory, SubCategory, Post


def pageNotFound(request, exception):
    response = render(request, '404.html')
    response.status_code = 404
    return response


class HomePageView(TemplateView):

    template_name = 'main/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = BlogCategory.objects.all()
        context['title'] = 'Главная'
        context['categories'] = categories
        return context


def category_detail(request, slug):
    category = get_object_or_404(BlogCategory, slug=slug)  # Category
    last_post = Post.objects.filter(category=OuterRef('pk')).order_by('-created_at')
    subcategories = SubCategory.objects.filter(category=category.id).annotate(last_post=Max('post__created_at'),
                                                                              num_posts=Count(
                                                                                  'post__author__user_name'),
                                                                              post_text=Subquery(
                                                                                  last_post.values('title')[:1]),
                                                                              post_author=Subquery(
                                                                                  last_post.values('author__user_name')[
                                                                                  :1])
                                                                              ).select_related('category')

    context = {'category': category, 'subcategories': subcategories, 'title': category}
    return render(request, 'main/category.html', context=context)


def subcategory_post(request, subcategory_slug):
    subcategory = get_object_or_404(SubCategory, slug=subcategory_slug)
    posts = Post.objects.filter(category=subcategory.id)

    # Paginator
    paginator = Paginator(posts, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.method == 'POST':
        form = AddCommentForm(request.POST)
        if form.is_valid():
            user = request.user
            text = request.POST.get('text')
            title = request.POST.get('title')
            subcategory_id = SubCategory.objects.get(slug=subcategory_slug).id
            context = {'posts': posts, 'title': subcategory, 'form': form, 'user_name': user.user_name}


            Post.objects.create(author=user, text=text, title=title, category_id=subcategory_id)

    else:
        form = AddCommentForm()

    if request.user.is_authenticated:
        user_name = Author.objects.get(user_name=request.user.user_name)
        context = {'page_obj': page_obj, 'title': subcategory, 'form': form, 'user_name': user_name}
    else:
        context = {'page_obj': page_obj, 'title': subcategory, 'form': form}
    return render(request, 'main/posts.html', context=context)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    redirect_field_name = 'login'
    form_class = AddCommentForm
    template_name = 'main/edit_post.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["button_label"] = 'Обновить комментарий'
        return context

    def post(self, request, *args, **kwargs):
        user_id_from_request = request.user.id
        post_id = kwargs.get('pk')
        title, text = request.POST.get('title'), request.POST.get('text')

        post = get_object_or_404(Post, pk=post_id)

        if user_id_from_request != post.author_id:  # Prevents URL injection
            raise Http404
        else:
            post.title, post.text = title, text
            post.save()
            messages.success(request, message='Пост успешно отредактирован')
            return render(request, self.template_name, context={'form': self.form_class(initial=
                                                                                        {'title': title, 'text': text}),
                                                                'button_label': 'Обновить запись'})


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'main/post_delete.html'

    def post(self, request, *args, **kwargs):
        user_id_from_request = request.user.id
        post_id = kwargs.get('pk')
        post = get_object_or_404(Post, pk=post_id)

        if user_id_from_request != post.author_id:  # Prevents URL injection
            raise Http404
        else:
            post.delete()
            return HttpResponseRedirect('/')


class FeedBackView(LoginRequiredMixin, FormView):
    form_class = FeedBackForm
    success_url = '/'
    template_name = 'main/feedback_form.html'

    def form_valid(self, form):
        message = render_to_string(
            "main/email_to_admin_template.html",
            {
                'user_email': self.request.user.email,
                'message_text': form.cleaned_data['text']
            },
        )
        mail_admins(subject='Обратная связь', message=message, fail_silently=False)
        return super().form_valid(form)

forum/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</head>
<body>


<!-- HEADER START -->

<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'main:home' %}" class="nav-link px-2 text-secondary">Главная</a></li>
          <li><a href="{% url 'authors:author_list_view' %}" class="nav-link px-2 text-white">Авторы</a></li>
          <li><a href="{% url 'main:feedback' %}" class="nav-link px-2 text-white">Вопросы нам</a></li>
          <li><a href="#" class="nav-link px-2 text-white">О сайте</a></li>

            {% if user.is_superuser %}
          <li><a href="{% url 'admin:index' %}" class="nav-link px-2 text-white">Админ панель</a></li>
            {% endif %}

            {% if user.is_authenticated %}
          <li><a href="{% url 'account:personal_profile' %}" class="nav-link px-2 text-white">Профиль</a></li>
            {% endif %}
          </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" method="get" action="{% url 'authors:search_author' %}">
            <input type="search" name="q" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>


          {% if not user.is_authenticated %}
        <div class="text-end">
          <a href="{% url 'account:login' %}"button type="button" class="btn btn-outline-light me-2">Вход</a>
          <a href="{% url 'account:register' %}" button type="button" class="btn btn-warning">Регистрация</a>
        </div>
          {% else %}
          <div class="text-end">
            <a href="{% url 'account:logout' %}"button type="button" class="btn btn-outline-light me-2">Выход</a>

          </div>
          {% endif %}
      </div>
    </div>
  </header>

<!--HEADER END-->


<!-- CONTENT START-->
{% block content %}

{% endblock %}
<!--CONTENT END-->


<!-- FOOTER START -->

<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-body-secondary">&copy; 2023 Company, Inc</p>

    <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
    </a>

    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="{% url 'main:home' %}" class="nav-link px-2 text-body-secondary">Главная</a></li>
      <li class="nav-item"><a href="{% url 'authors:author_list_view' %}" class="nav-link px-2 text-body-secondary">Авторы</a></li>
      <li class="nav-item"><a href="{% url 'main:feedback' %}" class="nav-link px-2 text-body-secondary">Вопросы нам</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">О сайте</a></li>
    </ul>
  </footer>
</div>

<!-- FOOTER END -->


</body>
</html>

forum/main/templates/main/category.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<link rel="stylesheet" href="{% static 'main/css/subcat_styles.css' %}">

<h2 class="category_headline">{{ category.category_name }}</h2>

{% for subcategory in subcategories %}
<hr>
<div class="subforum-section">
    <div class="subforum-description subforum-column">
        <h4><a href="{{ subcategory.get_absolute_url }}">{{ subcategory }}</a></h4>
        {% if subcategory.post_text %}
        <p>{{ subcategory.post_text }}</p>
        {% endif %}
    </div>
    <div class="subforum-stats subforum-column center">
        <span>Количество постов: {{ subcategory.num_posts }}</span>
    </div>
    <div class="subforum-info subforum-column">
        {% if subcategory.last_post %}
        Автор последнего поста: <a href="">{{ subcategory.post_author }}</a>
        <br>
        <small>Последний пост: {{ subcategory.last_post }}</small>

        {% endif %}
    </div>
</div>
<hr>
{% endfor %}

{% endblock %}

forum/main/templates/main/edit_post.html
{% extends 'main/base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}

<style>
    .form {
    max-width: 50%;
    margin-left: 25%;
}
</style>


<div class="form">{% include 'main/message_form.html' %}</div>


{% endblock %}

forum/main/templates/main/email_to_admin_template.html
{% autoescape off %}

Пользователь с почтой {{ user_email }} отправил вам сообщение:
{{ message_text }}

{% endautoescape %}

forum/main/templates/main/feedback_form.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
    
<link rel="stylesheet" href="{% static 'main/css/forms.css' %}">

<div class="form">
    <form class="account-form px-4 pt-4" method="post" enctype="multipart/form-data">


        {% csrf_token %}


        {{ form.as_p }}



         <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"
                        value="Save changes"> Отправить письмо
        </button>

    </form>

</div>

{% endblock %}

forum/main/templates/main/index.html
{% extends 'main/base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Категории</h1>
        <p class="lead text-body-secondary">Знакомьтесь с людьми, оставляйте посты, общайтесь, делитесь новостями..</p>
        <p>
            {% if user.is_authenticated %}
          <a href="{% url 'account:personal_profile' %}" class="btn btn-primary my-2">Ваша страница</a>
          <a href="{% url 'account:edit_details' %}" class="btn btn-secondary my-2">Редактировать профиль</a>
            {% else %}
            <a href="{% url 'account:login' %}" class="btn btn-primary my-2">Войти</a>
          <a href="{% url 'account:register' %}" class="btn btn-secondary my-2">Зарегистрироваться</a>
            {% endif %}
        </p>
      </div>
    </div>
  </section>


<div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for category in categories %}
        <div class="col">
          <div class="card shadow-sm">


            {% if not category.category_photo %}
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            {% else %}
            <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ category.category_photo.url }}">
            {% endif %}


            <div class="card-body">
              <p class="card-text">{{ category.category_name }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{{ category.get_absolute_url }}"><button type="button" class="btn btn-sm btn-outline-secondary">Перейти</button></a>
                </div>
                <small class="text-body-secondary"></small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>


{% endblock %}

forum/main/templates/main/message_form.html
{% load static %}
{% block content %}




<link rel="stylesheet" href="{% static 'main/css/forms.css' %}">

<form class="account-form px-4 pt-4" method="post" enctype="multipart/form-data">

    {% if form.is_valid %}
    <div class="alert alert-primary" role="alert">
        Комментарий оставлен!
    </div>
    {% endif %}

    {% if form.errors %}
    {% for field in user_form %}
    {% for error in field.errors %}
    <div class="alert alert-primary" role="alert">
        {{ error }}
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}

    {% if messages %}
    <div class="alert alert-warning" alert="{{ messages.tags }}" role="alert">
        {% for message in messages %}
        {{ message|safe }}
        {% endfor %}
    </div>
    {% endif %}

    {% csrf_token %}

    <label class="small font-weight-bold">{{ form.title.label}}</label>
    {{ form.title }}

    <label class="small font-weight-bold">{{ form.text.label }}</label>
    {{ form.text }}



    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"
                        value="Save changes">{% block button %}
        {% if button_label %}
        {{ button_label }}
        {% else %}
        Оставить комментарий
        {% endif %}
        {% endblock %}
    </button>

</form>




{% endblock %}

forum/main/templates/main/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

forum/main/templates/main/post_delete.html
{% extends 'main/base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}

<style>
    .form {
    max-width: 50%;
    margin-left: 25%;
}
</style>


<div class="form">
    <form method="post">
        {% csrf_token %}
    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"
                        value="Save changes">Удалить запись
    </button>
    </form>
</div>

{% endblock %}

forum/main/templates/main/posts.html
{% extends 'main/base.html' %}
{% load static %}
{% block title %} {{ title }} {% endblock %}
{% block content %}

<link rel="stylesheet" href="{% static 'main/css/forms.css' %}">
<link rel="stylesheet" href="{% static 'main/css/posts.css' %}">
<div class="content-text">
    <ul class="list-articles">
        {% for p in page_obj %}
        <li>
            <div class="article-panel">

                {% if p.author == user_name %}
                <a href="{{ p.get_absolute_url }}" style="color: midnightblue"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                </svg></a>
                <a href="{% url 'main:delete_post' p.id %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                  <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                  <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                </svg></a>
                {% endif %}

                Автор: <a href="{{ p.author.get_absolute_url }}">{{ p.author }}</a>

                <p class="last">Опубликовано: {{p.created_at|date:"d-m-Y H:i:s"}}</p>

            </div>

            <h2>{{p.title}}</h2>
            {% autoescape on %}

            {% endautoescape %}
            <div class="clear"></div>
            {{ p.text }}
          <p class="link-read-post"><a href="#formReview" onclick="addReview('{{ p.author }}')">Ответить на пост</a></p>
        </li>
        {% endfor %}
    </ul>
</div>

{% if user.is_authenticated %}
<div class="form">
    <form class="account-form px-4 pt-4" method="post" enctype="multipart/form-data">

    {% if form.is_valid %}
    <div class="alert alert-primary" role="alert">
        Комментарий оставлен!
    </div>
    {% endif %}

    {% if form.errors %}
    {% for field in user_form %}
    {% for error in field.errors %}
    <div class="alert alert-primary" role="alert">
        {{ error }}
    </div>
    {% endfor %}
    {% endfor %}
    {% endif %}
v
    {% if messages %}
    <div class="alert alert-warning" alert="{{ messages.tags }}" role="alert">
        {% for message in messages %}
        {{ message|safe }}
        {% endfor %}
    </div>
    {% endif %}

    {% csrf_token %}

    <label class="small font-weight-bold">{{ form.title.label}}</label>
    {{ form.title }}

    <label class="small font-weight-bold">{{ form.text.label }}</label>
    {{ form.text }}



    <button class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"
                        value="Save changes">{% block button %}
        {% if button_label %}
        {{ button_label }}
        {% else %}
        Оставить комментарий
        {% endif %}
        {% endblock %}
    </button>

</form>
</div>
{% else %}
<div style="margin-left: 30%; margin-top: 2%"><a href="{% url 'account:login' %}" style="color: black"><h4>Войдите в систему прежде чем оставлять комментарии</h4></a></div>
{% endif %}


{% include 'main/pagination.html' %}



<script>
    function addReview(author, id) {
        document.getElementById('exampleFormControlTextarea1').innerText = `${author}, `;
        document.getElementById('exampleFormControlTextarea1').scrollIntoView();
    }
</script>

{% endblock %}